### ISSUE TITLE
Error when enable Debugger

### ISSUE THREAD

**Issue by mdestafadilah** [hibbitts-design/grav-skeleton-course-hub#6]
Hi, thanks for your sekeletons before. it's much for me for study about GravCMS.

I want to debug/ dump some of variable, but when enable it in system.yaml

```yaml
debugger:
  enabled: true
  provider: clockwork
  censored: false
  shutdown:
    close_connection: true
  twig: true
```

its show error 

```bash
Server Error
Sorry, something went terribly wrong!

0 - Call to a member function get() on null
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.
```

when i'm chekc logs folder, it's say like this

```yaml
[2022-02-19 07:34:12] grav.DEBUG: Flex: User index updated, 1 objects (1 added, 0 updated, 0 removed). [] []
```

have you try debugger, or dump() for check variable?
